name: Make workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install meson shellcheck
    - name: Initialize submodules
      run: |
        git submodule update --init --recursive
    - name: Lint using Shellcheck
      run: |
        shellcheck configure.sh
    - name: Make System Package
      run: |
        ./configure.sh --prefix=/usr
        sudo make PREFIX=/usr install
